version: "3.0"

services:
    database:
        image: postgres
        restart: unless-stopped
        expose:
            - "5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app

    frontend:
        build: Angular/leo-survey/
        restart: unless-stopped
        hostname: frontend
        ports:
            - "8080:80"
        links: 
            - backend
        depends_on: 
            - backend

    backend:
        image: lsadmin/leo-survey:1.0-SNAPSHOT
        restart: unless-stopped
        hostname: backend
        ports:
            - "8443:8080"
        links:
            - database
        depends_on:
            - database       
